[package]

name = "haskell-compiler"
version = "0.0.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[[bin]]

name = "haskell-compiler"
path = "Test.hs"

[dependencies]
log = "0.3.6"
getopts = "0.2.14"
